// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIPCdw6gQDP0YMm0RBJV4m9inn9sEGves',
    appId: '1:636182048115:web:6586d5e2869eb5bc0ca906',
    messagingSenderId: '636182048115',
    projectId: 'learn-french-with-msu-ibrahim',
    authDomain: 'learn-french-with-msu-ibrahim.firebaseapp.com',
    storageBucket: 'learn-french-with-msu-ibrahim.appspot.com',
    measurementId: 'G-41LS9NZEEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrTXkVSZ0btYDwTadI1YSk3hikQU3sAxY',
    appId: '1:636182048115:android:7f9cd4a7180919a30ca906',
    messagingSenderId: '636182048115',
    projectId: 'learn-french-with-msu-ibrahim',
    storageBucket: 'learn-french-with-msu-ibrahim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPlpqlzoLdGvPeGjSgTK3v3AyQe9jqoAc',
    appId: '1:636182048115:ios:fc240e6980d31c770ca906',
    messagingSenderId: '636182048115',
    projectId: 'learn-french-with-msu-ibrahim',
    storageBucket: 'learn-french-with-msu-ibrahim.appspot.com',
    iosBundleId: 'com.example.learnfrenchwithmsuibrahim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPlpqlzoLdGvPeGjSgTK3v3AyQe9jqoAc',
    appId: '1:636182048115:ios:fc240e6980d31c770ca906',
    messagingSenderId: '636182048115',
    projectId: 'learn-french-with-msu-ibrahim',
    storageBucket: 'learn-french-with-msu-ibrahim.appspot.com',
    iosBundleId: 'com.example.learnfrenchwithmsuibrahim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIPCdw6gQDP0YMm0RBJV4m9inn9sEGves',
    appId: '1:636182048115:web:c8b1a031a98a48460ca906',
    messagingSenderId: '636182048115',
    projectId: 'learn-french-with-msu-ibrahim',
    authDomain: 'learn-french-with-msu-ibrahim.firebaseapp.com',
    storageBucket: 'learn-french-with-msu-ibrahim.appspot.com',
    measurementId: 'G-2566W9JB5L',
  );
}
